openapi: 3.0.1
info:
  description: "This is the definition for general components API, Labs version"
  version: "1.0.0"
  title: "General Components Labs API"


components:
  schemas:
    Balance:
      type: object
      description: The balance object
      properties:
        id:
          type: number
          description: The id
        code:
          type: string
          description: The code
        user:
          type: string
          description: The user
        average:
          type: number
          description: The average
        current:
          type: number
          description: The current
        active:
          type: boolean
          description: The active
        cuttofDate:
          type: string
          description: The cuttofDate
          format: date

    Product:
      type: object
      description: "The product object"
      properties:
        id:
          type: string
          description: "The product ID"
        name:
          type: string
          description: "The product name"
        description:
          type: string
          description: "The product description"
        category:
          type: string
          description: "The product category"
        price:
          type: number
          description: "The product price"
        image:
          type: string
          description: "The product image"
        stock:
          type: number
          description: "The product stock"
        available:
          type: boolean
          description: "The product availability"