parameters:
  - name: PROJECT_KEY
    type: string
    default: 'kc-labs-app'
  - name: DOCKER_IMAGE
    type: string
    default: 'kevdev105030/osnebula:20230930145215'
  - name: PROJECT_TYPE
    type: string
    default: 'java_serverless'

pool: 'Azure Pipelines'

variables:
  - group: GENERAL_DEVOPS_EJL

trigger:
  branches:
    include:
      - develop
      - dev1-kec
      - dev-ejl

resources:
  repositories:
    - repository: templates
      type: git
      name: 'kc-cloud-devops'
      ref: 'dev1-ejl'

stages:
  - template: templates/stages/microserviceStage.yml@templates
    parameters:
      PROJECT_KEY: ${{ parameters.PROJECT_KEY }}
      DOCKER_IMAGE: ${{ parameters.DOCKER_IMAGE }}
      PROJECT_TYPE: ${{ parameters.PROJECT_TYPE }}
