parameters:
  - name: PROJECT_KEY
    type: string
    default: 'kc-labs-app'
  - name: DOCKER_IMAGE
    type: string
    default: 'kevdev105030/osnebula:20230917210615'
  - name: PROJECT_TYPE
    type: string
    default: 'java_serverless'

pool: 'Azure Pipelines'

variables:
  - group: GENERAL_DEVOPS

trigger:
  branches:
    include:
      - develop


resources:
  repositories:
    - repository: templates
      type: git
      name: 'kc-cloud-devops'
      ref: 'refs/tags/v0.0.1'

stages:
  - template: templates/stages/microserviceStage.yml@templates
    parameters:
      PROJECT_KEY: ${{ parameters.PROJECT_KEY }}
      DOCKER_IMAGE: ${{ parameters.DOCKER_IMAGE }}
      PROJECT_TYPE: ${{ parameters.PROJECT_TYPE }}
