version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dev-kec-labs"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xmz9a9vxe11b"
s3_prefix = "dev-kec-labs"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
