AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Main SAM Template for kc-labs-serverless, using AWS Serverless Application Model

Parameters:
  EnvironmentId:
    Type: String
    Description: Environment ID

  LambdaAliasProduction:
    Type: String
    Description: Lambda Alias for Production

  LambdaAliasBeta:
    Type: String
    Description: Environment alias

  LogRetentionInDays:
    Type: String
    Description: Log retention in days

  LambdaAuthorizer:
    Type: String
    Description: Lambda Authorizer
  
  ProvisionedConcurrencyConfigEnabled:
    Type: String
    Description: Enable Provisioned Concurrency Config


Resources:
  LambdasInfraestructure:
    Type: AWS::Serverless::Application
    Properties:
      Location: kc-labs-app/labs-template.yaml
      Parameters:
        EnvironmentId: !Ref EnvironmentId
        LambdaAliasProduction: !Ref LambdaAliasProduction
        LambdaAliasBeta: !Ref LambdaAliasBeta
        LogRetentionInDays: !Ref LogRetentionInDays
        LambdaAuthorizer: !Ref LambdaAuthorizer
        ProvisionedConcurrencyConfigEnabled: !Ref ProvisionedConcurrencyConfigEnabled
        ApiGatewayResponseMessage400: "The message is not properly formatted."
        ApiGatewayResponseMessage401: "You are not authorized to access this resource."
        ApiGatewayResponseMessage403: "The request has been denied."
        ApiGatewayResponseMessage404: "The object not found."
        ApiGatewayResponseMessage405: "The method is not allowed."
        ApiGatewayResponseMessage409: "The request had a conflict."
        ApiGatewayResponseMessage429: "Too many requests have been made."
        ApiGatewayResponseMessage500: "An error occurred during the request."