AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  kc-labs-serverless

  Sample SAM Template for kc-labs-serverless

Parameters:
  LambdaPath:
    Type: String
    Description: Path to the Lambda function code
    Default: /labs/greetings

Globals:
  Function:
    CodeUri: kc-labs-app
    Timeout: 20
    Tracing: Active
    Runtime: java11
    MemorySize: 512
    Architectures:
      - x86_64
  Api:
    TracingEnabled: True

Resources:
  LabsGreetingsGETHelloLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: kc-labs-app
      Handler: com.kc.cloud.labs.aws.lambda.greetings.LabsGreetingsGETHello::handleRequest
      Environment:
        Variables:
          PARAM1: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        LabsGreetingsGETHelloApi:
          Type: Api
          Properties:
            Path: !Sub ${LambdaPath}/hello
            Method: get

  LabsGreetingGETNameLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.kc.cloud.labs.aws.lambda.greetings.LabsGreetingGETName::handleRequest
      FunctionName: !Sub ${AWS::StackName}-LabsGreetingGETNameLambda
      Environment:
        Variables:
          PARAM1: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        LabsGreetingGETNameApi:
          Type: Api
          Properties:
            Path: !Sub ${LambdaPath}/name
            Method: get