AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  kc-labs-serverless

  Sample SAM Template for kc-labs-serverless

Globals:
  Function:
    Timeout: 20
    Tracing: Active
  Api:
    TracingEnabled: True

Resources:
  LabsGreetingsGETHelloLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: kc-labs-app
      Handler: com.kc.cloud.labs.aws.lambda.greetings.LabsGreetingsGETHello::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        LabsGreetingsGETHelloApi:
          Type: Api
          Properties:
            Path: /labs/greetings/hello
            Method: get

  LabsGreetingGETNameLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: kc-labs-app
      Handler: com.kc.cloud.labs.aws.lambda.greetings.LabsGreetingGETName::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        LabsGreetingGETNameApi:
          Type: Api
          Properties:
            Path: /labs/greetings/name
            Method: get