AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  kc-labs-serverless
  Sample SAM Template 

Globals:
  Function:
    CodeUri: kc-labs-app
    Timeout: 20
    Tracing: Active
    Runtime: java11
    MemorySize: 512
    Architectures:
      - x86_64
  Api:
    TracingEnabled: True

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ./specs/open_api.yaml
    
  LabsCustomersGETAllLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.kc.cloud.labs.aws.lambda.customers.LabsCustomersGETAll::handleRequest
      FunctionName: !Sub ${AWS::StackName}-LabsCustomersGETAll
      Environment:
        Variables:
          PARAM1: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        EventApiLabsCustomersGETAll:
          Type: Api
          Properties:
            Path: /labs/customers
            Method: get
            RestApiId: !Ref ApiGatewayApi

  LabsCustomersGETByIdLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.kc.cloud.labs.aws.lambda.customers.LabsCustomersGETById::handleRequest
      FunctionName: !Sub ${AWS::StackName}-LabsCustomersGETById
      Environment:
        Variables:
          PARAM1: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        EventApiLabsCustomersGETById:
          Type: Api
          Properties:
            Path: /labs/customers/{id}
            Method: get
            RestApiId: !Ref ApiGatewayApi

  LabsCustomersPSTCreateLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.kc.cloud.labs.aws.lambda.customers.LabsCustomersPSTCreate::handleRequest
      FunctionName: !Sub ${AWS::StackName}-LabsCustomersPSTCreate
      Environment:
        Variables:
          PARAM1: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        EventApiLabsCustomersPSTCreate:
          Type: Api
          Properties:
            Path: /labs/customers
            Method: post
            RestApiId: !Ref ApiGatewayApi