AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  kc-labs-serverless

  Sample SAM Template for kc-labs-serverless

Globals:
  Function:
    CodeUri: kc-labs-app/target/kc-labs-app-1.0.jar
    Timeout: 20
    Tracing: Active
    Runtime: java11
    MemorySize: 512
    Architectures:
      - x86_64
  Api:
    TracingEnabled: True

Resources:
  LabsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub LabsLayer-${AWS::StackName}
      Description: Layer libs for kc-labs-serverless
      ContentUri: kc-labs-app/dependencies
      CompatibleRuntimes:
        - java11
        - java8
      CompatibleArchitectures:
        - x86_64
      LicenseInfo: "MIT"
      RetentionPolicy: Retain

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ./specs/labs_api.yaml

  LabsGreetingsGETHelloLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.kc.cloud.labs.aws.lambda.greetings.LabsGreetingsGETHello::handleRequest
      FunctionName: !Sub ${AWS::StackName}-LabsGreetingsGETHelloLambda
      Layers:
        - !Ref LabsLayer
      Environment:
        Variables:
          PARAM1: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        EventApi:
          Type: Api
          Properties:
            Path: /labs/greetings/hello
            Method: get
            RestApiId: !Ref ApiGatewayApi

  LabsGreetingGETNameLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.kc.cloud.labs.aws.lambda.greetings.LabsGreetingGETName::handleRequest
      FunctionName: !Sub ${AWS::StackName}-LabsGreetingGETNameLambda
      Layers:
        - !Ref LabsLayer
      Environment:
        Variables:
          PARAM1: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        EventApi:
          Type: Api
          Properties:
            Path: /labs/greetings/name/{value}
            Method: get
            RestApiId: !Ref ApiGatewayApi

  LabsBalancesGETByIdLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.kc.cloud.labs.aws.lambda.balances.LabsBalancesGETById::handleRequest
      FunctionName: !Sub ${AWS::StackName}-LabsBalancesGETByIdLambda
      Layers:
        - !Ref LabsLayer
      Environment:
        Variables:
          PARAM1: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        EventApi:
          Type: Api
          Properties:
            Path: /labs/balances/{id}
            Method: get
            RestApiId: !Ref ApiGatewayApi