build-lambda:
	cp -rf ./target/classes/* $(ARTIFACTS_DIR)/

build-LabsGreetingsGETHelloLambda: build-lambda

build-LabsGreetingGETNameLambda: build-lambda

build-LabsBalancesGETByIdLambda: build-lambda
